spring:
  application:
    name: dgh-admin
  profiles:
    active: dev
  mvc: 
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true
      charset: UTF-8
      force-response: true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations:
    - classpath:/static/
  
